
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: libtext-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/libtext
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: A c++ library for text processing for searching

source:
  git_url: ../

outputs:
  - name: libtext
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      string: "h{{ GIT_DESCRIBE_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('libtext', exact=True) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - sysroot_linux-64 =2.17  # [linux64]
        - cmake >=3.20, <=3.23
        - turbo
      host:
        - sysroot_linux-64 =2.17  # [linux64]
        - turbo
      run:
        - sysroot_linux-64 =2.17  # [linux64]
        - turbo

    test:
      commands:
      #  - test -f $PREFIX/lib/libturbo.so              # [linux]
      #  - test -f $PREFIX/lib/libturbo.dylib           # [osx]
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
